// Fill out your copyright notice in the Description page of Project Settings.

#include "Trap/ExplosionTrap.h"
#include "PhysicsEngine/RadialForceComponent.h"
#include "Components/SphereComponent.h"
#include "GameFramework/Character.h"
#include "NiagaraComponent.h"
#include "NiagaraFunctionLibrary.h"
#include "Character/BrickCharacter.h"
#include "Components/WidgetComponent.h"
#include "Kismet/GameplayStatics.h"
#include "TimerManager.h"

AExplosionTrap::AExplosionTrap()
{
    // Collision ì´ˆê¸°í™”
    InitCollision(true, false);

    // í­ë°œ ë¬¼ë¦¬ í˜ì„ ì£¼ê¸° ìœ„í•œ RadialForceComponent ìƒì„±
    RadialForceComp = CreateDefaultSubobject<URadialForceComponent>(TEXT("RadialForceComp"));
    RadialForceComp->SetupAttachment(RootComponent);
    RadialForceComp->Radius = ExplosionRadius;
    RadialForceComp->bImpulseVelChange = true;
    RadialForceComp->bIgnoreOwningActor = true;
    RadialForceComp->ImpulseStrength = ExplosionForce;
}

void AExplosionTrap::ActiveTrap(ACharacter* Target)
{
    // ë©”ì‹œ ìˆ¨ê¸°ê³  ì¶©ëŒ ì œê±°
    if (StaticMeshComp)
    {
        StaticMeshComp->SetVisibility(false);
        StaticMeshComp->SetCollisionEnabled(ECollisionEnabled::NoCollision);
    }
    InitCollision(false, false);
    // í­ë°œ ì´í™íŠ¸ ì¬ìƒ
    if (ExplosionNiagaraSystem)
    {
        UNiagaraComponent* NiagaraComponent = UNiagaraFunctionLibrary::SpawnSystemAtLocation(
            GetWorld(),
            ExplosionNiagaraSystem,
            GetActorLocation(),
            GetActorRotation()
        );

        if (NiagaraComponent)
        {
            NiagaraComponent->OnSystemFinished.AddDynamic(this, &AExplosionTrap::OnExplosionFinished);
        }
    }

    // ğŸ”Š í­ë°œ ì‚¬ìš´ë“œ ì¬ìƒ
    if (ExplosionSound)
    {
        UGameplayStatics::PlaySoundAtLocation(this, ExplosionSound, GetActorLocation());
    }


    RadialForceComp->FireImpulse();


    if (Target && StarEffectNiagaraSystem)
    {
        UNiagaraComponent* StarEffect = UNiagaraFunctionLibrary::SpawnSystemAttached(
            StarEffectNiagaraSystem,
            Target->GetMesh(),
            FName("Head_bone"),
            FVector(0.f, 0.f, 20.f),
            FRotator::ZeroRotator,
            EAttachLocation::KeepRelativeOffset,
            false 
        );

        if (StarEffect && GetWorld())
        {
            FTimerHandle StarDestroyHandle;
            GetWorld()->GetTimerManager().SetTimer(
                StarDestroyHandle,
                FTimerDelegate::CreateLambda([StarEffect]()
                    {
                        StarEffect->DestroyComponent();
                    }),
                8.0f, false
            );
        }

    }
    if (Target && Target->IsPlayerControlled())
    {
        UUserWidget* Widget = nullptr;

        Widget = Cast<UUserWidget>(Target->FindComponentByClass<UWidgetComponent>());

        if (!Widget)
        {
            
            ABrickCharacter* MyChar = Cast<ABrickCharacter>(Target);
            if (MyChar && MyChar->DamageInstance)
            {
                Widget = MyChar->DamageInstance;
            }
        }

        if (Widget)
        {
            UFunction* FlashFunc = Widget->FindFunction(TEXT("PlayFlash"));
            if (FlashFunc)
            {
                Widget->ProcessEvent(FlashFunc, nullptr);
            }
        }
    }
}

void AExplosionTrap::OnExplosionFinished(UNiagaraComponent* FinishedComponent)
{
    // íŠ¸ë© ì œê±°
    Destroy();
}
